# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:

name: test-coverage.yaml

permissions: read-all

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout base branch
        uses: actions/checkout@v4
        with:
          ref: main
          path: base-branch

      - name: Checkout current branch
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Setup R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::covr
            any::xml2
            github::dragosmg/covr2gh
            any::stringr
            any::fs
          needs: coverage

      - name: Test coverage
        run: |
          file_path <- file.path(normalizePath(Sys.getenv("RUNNER_TEMP"), winslash = "/"), "package")

          head_cov <- covr::package_coverage(
            quiet = FALSE,
            clean = TRUE,
            install_path = file_path
          )
          print("==============")
          print("head coverage:")
          print("==============")
          print(head_cov)
          print("==============")

          # fs::dir_delete(file_path)

          system("git checkout main")

          print("==============")
          print("base coverage:")
          print("==============")
          base_cov <- covr::package_coverage(
            quiet = FALSE,
            clean = TRUE,
            install_path = file_path
          )

          print(base_cov)
          print("==============")

          owner_repo <- stringr::str_split_1("${{ github.repository }}", "/")
          print(owner_repo[[1]])
          print(owner_repo[[2]])

          github_comment <- covr2gh::compose_comment(
            head_coverage = head_cov,
            base_coverage = base_cov,
            owner = owner_repo[[1]],
            repo = owner_repo[[2]],
            pr_number = ${{ github.event.pull_request.number }}
          )

          print(github_comment)

        shell: Rscript {0}

      # - uses: codecov/codecov-action@v5
      #   with:
      #     # Fail if error if not on PR, or if on PR and token is given
      #     fail_ci_if_error: ${{ github.event_name != 'pull_request' || secrets.CODECOV_TOKEN }}
      #     files: ./cobertura.xml
      #     plugins: noop
      #     disable_search: true
      #     token: ${{ secrets.CODECOV_TOKEN }}

      - name: test-coverage
        id: coverage
        run: |
          markdown_cov_diff <- function(head, main) {
          group <- "filename"
          by = "line"
          sig_num <- 2

          tally_head <- covr::tally_coverage(head, by = by)
          tally_main <- covr::tally_coverage(main, by = by)

          percs_head <- tapply(tally_head$value, tally_head[[group]], FUN = function(x) sum(x > 0) / length(x) * 100)
          percs_main <- tapply(tally_main$value, tally_main[[group]], FUN = function(x) sum(x > 0) / length(x) * 100)
          percs_diff <- unname(percs_head - percs_main)

          ttl_perc_head <- covr::percent_coverage(tally_head, by = by)
          ttl_perc_main <- covr::percent_coverage(tally_main, by = by)
          ttl_perc_diff <- ttl_perc_head - ttl_perc_main

          percs_head <- format(percs_head, digits = sig_num)
          percs_main <- format(percs_main, digits = sig_num)
          percs_diff <- paste0(ifelse(percs_diff < 0, ":small_red_triangle_down: ", ""), ifelse(percs_diff > 0, ":arrow_up: ", ""), format(percs_diff, digits = sig_num))

          ttl_perc_head <- format(ttl_perc_head, digits = sig_num)
          ttl_perc_main <- format(ttl_perc_main, digits = sig_num)
          ttl_perc_diff <- paste0(ifelse(ttl_perc_diff < 0, ":small_red_triangle_down: ", ""), ifelse(ttl_perc_diff > 0, ":arrow_up: ", ""), format(ttl_perc_diff, digits = sig_num))

          paste0(
            "<details>\n",
            "<summary>Coverage Report</summary>\n\n",
            "|file|head|main|diff|\n|",
            " :-- | --: | --: | --: |\n",
            paste0("|Overall|", ttl_perc_head, "%|", ttl_perc_main, "%|", ttl_perc_diff, "%|", "\n"),
            paste0("|", names(percs_head), "|", percs_head, "%|", percs_main, "%|", percs_diff, "%|", collapse = "\n"),
            "\n",
            "</details>"
            )
          }

          head <- covr::package_coverage()
          system2("git", c("checkout", "main"))
          main <- covr::package_coverage()
          writeLines(markdown_cov_diff(head, main), "coverage-report.md")
        shell: Rscript {0}

      - name: Show testthat output
        if: always()
        run: |
          ## --------------------------------------------------------------------
          find '${{ runner.temp }}/package' -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-test-failures
          path: ${{ runner.temp }}/package

      - name: Upload coverage data
        if: github.event_name != 'pull_request'
